// Generated by gencpp from file custom_msgs/SerialRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_SERIALREQUEST_H
#define CUSTOM_MSGS_MESSAGE_SERIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct SerialRequest_
{
  typedef SerialRequest_<ContainerAllocator> Type;

  SerialRequest_()
    : Code(0)
    , Length(0)
    , Buffer()  {
      Buffer.assign(0);
  }
  SerialRequest_(const ContainerAllocator& _alloc)
    : Code(0)
    , Length(0)
    , Buffer()  {
  (void)_alloc;
      Buffer.assign(0);
  }



   typedef uint16_t _Code_type;
  _Code_type Code;

   typedef uint16_t _Length_type;
  _Length_type Length;

   typedef boost::array<uint8_t, 64>  _Buffer_type;
  _Buffer_type Buffer;





  typedef boost::shared_ptr< ::custom_msgs::SerialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::SerialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SerialRequest_

typedef ::custom_msgs::SerialRequest_<std::allocator<void> > SerialRequest;

typedef boost::shared_ptr< ::custom_msgs::SerialRequest > SerialRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::SerialRequest const> SerialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::SerialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::SerialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/pi/Documents/ros_ws/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SerialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SerialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SerialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SerialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SerialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SerialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::SerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3caf2e11f9a4e075e8eb559468402d7";
  }

  static const char* value(const ::custom_msgs::SerialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3caf2e11f9a4e07ULL;
  static const uint64_t static_value2 = 0x5e8eb559468402d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::SerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/SerialRequest";
  }

  static const char* value(const ::custom_msgs::SerialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::SerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 Code\n\
uint16 Length\n\
uint8[64] Buffer\n\
";
  }

  static const char* value(const ::custom_msgs::SerialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::SerialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Code);
      stream.next(m.Length);
      stream.next(m.Buffer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::SerialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::SerialRequest_<ContainerAllocator>& v)
  {
    s << indent << "Code: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Code);
    s << indent << "Length: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Length);
    s << indent << "Buffer[]" << std::endl;
    for (size_t i = 0; i < v.Buffer.size(); ++i)
    {
      s << indent << "  Buffer[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Buffer[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_SERIALREQUEST_H
